language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install radon
    - pip install pep8
# command to run tests
script:
    - py.test
    - py.test --cov . --cov-report term-missing
after_success:
    - pep8 --statistics --count tests
    - pep8 --statistics --count src
    - radon raw src/.
    - radon raw tests/.
    - radon cc tests/.
    - radon cc src/.
    - radon mi tests/.
    - radon mi src/.
    - coveralls